services:

    db:
      image: postgres:17
      container_name: taskhub_db
      restart: unless-stopped
      environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      volumes:
      - postgres_data:/var/lib/postgresql/data
      ports:
      - "5432:5432"

    backend:
        build:
          context: ./backend
        container_name: taskhub_backend
        restart: unless-stopped
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
          - ./backend/src:/app
        ports:
          - "8000:8000"
        depends_on:
          - db

volumes:
    postgres_data:
